create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_nombre text not null,
  cliente_telefono text not null,
  cliente_correo text not null,
  direccion text,
  tipo_entrega text,
  metodo_pago text not null,
  productos jsonb not null default '[]'::jsonb,
  total numeric(12, 2) not null default 0,
  estado text not null default 'Nuevo'
    check (estado in ('Nuevo', 'Pendiente', 'Pagado', 'En preparación', 'Enviado', 'Entregado', 'Cancelado')),
  notas text,
  created_at timestamptz not null default now()
);

alter table public.pedidos enable row level security;

alter table public.pedidos drop constraint if exists pedidos_estado_check;
alter table public.pedidos add constraint pedidos_estado_check
  check (estado in ('Nuevo', 'Pendiente', 'Pagado', 'En preparación', 'Enviado', 'Entregado', 'Cancelado'));

drop policy if exists "clientes pueden crear pedidos" on public.pedidos;
create policy "clientes pueden crear pedidos"
on public.pedidos for insert
to anon, authenticated
with check (estado = 'Nuevo');

drop policy if exists "ventas puede leer pedidos" on public.pedidos;
create policy "ventas puede leer pedidos"
on public.pedidos for select
to authenticated
using ((auth.jwt() ->> 'email') = 'ventas@rubensdistribuidora.com');

drop policy if exists "ventas puede actualizar pedidos" on public.pedidos;
create policy "ventas puede actualizar pedidos"
on public.pedidos for update
to authenticated
using ((auth.jwt() ->> 'email') = 'ventas@rubensdistribuidora.com')
with check ((auth.jwt() ->> 'email') = 'ventas@rubensdistribuidora.com');

create index if not exists pedidos_created_at_idx on public.pedidos (created_at desc);
create index if not exists pedidos_estado_idx on public.pedidos (estado);
